apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::419763087940:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FQRSEG16R9ZR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-26T02:30:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2755"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3bdd199c-8e7d-4070-84c6-9967926a949d
