create-stack:
	aws cloudformation create-stack  --stack-name myFirstTest --region eu-north-1 --template-body file://myfirsttemplate.yml
update-stack:
	aws cloudformation update-stack  --stack-name myFirstTest --region eu-north-1 --template-body file://myfirsttemplate.yml
describe-stack:
	aws cloudformation describe-stacks --stack-name myFirstTest
delete-stack:
	aws cloudformation delete-stack --stack-name myFirstTest
